apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::103055791048:role/eksctl-eksctl-demo-nodegroup-ng-7-NodeInstanceRole-HAUZC2IL0V96
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::103055791048:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T12:30:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1556"
  uid: a225913a-3db2-4f93-a5c0-099c0ccaa0d9
